#include <time.h>
#include <dos.h>
#include <mem.h>
#include <process.h>
#include <stdlib.h>
#include <ctype.h>
#include <stdio.h>
#include <bios.h>
#include <dir.h>
#include <string.h>


#include "macrorun.h"
#include "macroinf.h"

#include "mroutine.h"
#include "sroutine.h"
#include "linklist.h"


#include "_file_.h"
#include "_page_.h"
#include "_show_.h"
#include "_tools_.h"
#include "_help_.h"

#include "hotkey.h"
